version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: visio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  
  visio:
    image: thewisepigeon/visio:latest
    container_name: server
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
