version: '3'

services:
  postgres:
    image: postgres
    networks:
        - proxymanager_default
    container_name: postgres
    environment:
      POSTGRES_DB: visio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    networks:
        - proxymanager_default
    container_name: redis
  
  visio:
    image: thewisepigeon/visio:latest
    networks:
        - proxymanager_default
    container_name: server
    depends_on:
      - postgres
      - redis
networks:
  proxymanager_default:
    external: true
