name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install tailwind dependencies
      run: npm ci

    - name: Compile css
      run: make build-css

    - name: Install Visio build dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install libdlib-dev libblas-dev libatlas-base-dev liblapack-dev libjpeg-turbo8-dev

    - name: Build binary
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
